import type { DocumentTemplate } from '@/lib/documents/types';

export const rentalAgreementTemplate: DocumentTemplate = {
  id: 'rental-agreement',
  name: 'Rental Agreement',
  templatePath: 'public/documents/contract-agreement.pdf',
  fieldGroups: [
    {
      id: 'reservation',
      name: 'Reservation Information',
      fields: [
        { key: 'rental_number', label: 'Agreement number', type: 'text' },
        { key: 'date_booked', label: 'Date booked', type: 'date' },
        { key: 'date_today', label: "Today's date", type: 'date' },
        { key: 'rental_start_datetime', label: 'Departure date & time', type: 'datetime' },
        { key: 'rental_end_datetime', label: 'Return date & time', type: 'datetime' },
        { key: 'miles_package', label: 'Miles package', type: 'text' },
        { key: 'free_miles', label: 'Free miles included', type: 'number', computed: true },
      ],
    },
    {
      id: 'insurance',
      name: 'Insurance Information',
      fields: [
        { key: 'insurance_policy', label: 'Policy number', type: 'text' },
        { key: 'insurance_type', label: 'Insurance type', type: 'text' },
        { key: 'insurance_company', label: 'Insurance company', type: 'text' },
      ],
    },
    {
      id: 'renter',
      name: 'Renter Information',
      fields: [
        { key: 'full_name', label: 'Full name', type: 'text' },
        { key: 'customer_number', label: 'Phone number', type: 'tel' },
        { key: 'renters_address', label: 'Address', type: 'text' },
        { key: 'renters_email', label: 'Email address', type: 'email' },
        { key: 'date_of_birth', label: 'Date of birth', type: 'date' },
        { key: 'customer_age', label: 'Age', type: 'number', computed: true },
        { key: 'license_number', label: 'License number', type: 'text' },
        { key: 'license_exp_date', label: 'License expiration', type: 'date' },
      ],
    },
    {
      id: 'additional_driver',
      name: 'Additional Driver',
      fields: [
        { key: 'additional_driver_name', label: 'Name', type: 'text' },
        { key: 'additional_driver_email', label: 'Email', type: 'email' },
        { key: 'additional_driver_phonenumber', label: 'Phone number', type: 'tel' },
        { key: 'additional_dob', label: 'Date of birth', type: 'date' },
        { key: 'additional_address', label: 'Address', type: 'text' },
        { key: 'additional_license', label: 'License number', type: 'text' },
      ],
    },
    {
      id: 'pickup_dropoff',
      name: 'Pickup & Drop-off',
      fields: [
        { key: 'pickup_service', label: 'Pickup location', type: 'text' },
        { key: 'pickup_miles', label: 'Pickup miles', type: 'number' },
        { key: 'pickup_price', label: 'Pickup charge', type: 'currency' },
        { key: 'dropoff_service', label: 'Drop-off location', type: 'text' },
        { key: 'dropoff_miles', label: 'Drop-off miles', type: 'number' },
        { key: 'dropoff_price', label: 'Drop-off charge', type: 'currency' },
      ],
    },
    {
      id: 'rental_charges',
      name: 'Rental Charges',
      hidden: true,
      fields: [
        { key: 'r_description_1', label: 'Line 1 description', type: 'text' },
        { key: 'r_rate_1', label: 'Line 1 rate type', type: 'text' },
        { key: 'r_days_1', label: 'Line 1 days', type: 'number' },
        { key: 'r_cost_per_day_1', label: 'Line 1 cost/day', type: 'currency' },
        { key: 'r_total_1', label: 'Line 1 total', type: 'currency' },
        { key: 'r_description_2', label: 'Line 2 description', type: 'text' },
        { key: 'r_rate_2', label: 'Line 2 rate type', type: 'text' },
        { key: 'r_days_2', label: 'Line 2 days', type: 'number' },
        { key: 'r_cost_per_day_2', label: 'Line 2 cost/day', type: 'currency' },
        { key: 'r_total_2', label: 'Line 2 total', type: 'currency' },
      ],
    },
    {
      id: 'extras',
      name: 'Extras & Add-ons',
      hidden: true,
      fields: [
        { key: 'e_description_1', label: 'Extra 1 description', type: 'text' },
        { key: 'e_days_1', label: 'Extra 1 days', type: 'number' },
        { key: 'e_cost_per_day_1', label: 'Extra 1 cost/day', type: 'currency' },
        { key: 'e_total_1', label: 'Extra 1 total', type: 'currency' },
        { key: 'e_description_2', label: 'Extra 2 description', type: 'text' },
        { key: 'e_days_2', label: 'Extra 2 days', type: 'number' },
        { key: 'e_cost_per_day_2', label: 'Extra 2 cost/day', type: 'currency' },
        { key: 'e_total_2', label: 'Extra 2 total', type: 'currency' },
        { key: 'e_description_3', label: 'Extra 3 description', type: 'text' },
        { key: 'e_days_3', label: 'Extra 3 days', type: 'number' },
        { key: 'e_cost_per_day_3', label: 'Extra 3 cost/day', type: 'currency' },
        { key: 'e_total_3', label: 'Extra 3 total', type: 'currency' },
        { key: 'e_description_4', label: 'Extra 4 description', type: 'text' },
        { key: 'e_days_4', label: 'Extra 4 days', type: 'number' },
        { key: 'e_cost_per_day_4', label: 'Extra 4 cost/day', type: 'currency' },
        { key: 'e_total_4', label: 'Extra 4 total', type: 'currency' },
        { key: 'e_description_5', label: 'Extra 5 description', type: 'text' },
        { key: 'e_days_5', label: 'Extra 5 days', type: 'number' },
        { key: 'e_cost_per_day_5', label: 'Extra 5 cost/day', type: 'currency' },
        { key: 'e_total_5', label: 'Extra 5 total', type: 'currency' },
      ],
    },
    {
      id: 'services',
      name: 'Services & Taxes',
      hidden: true,
      fields: [
        { key: 'sales_tax', label: 'Sales tax (8.9%)', type: 'currency' },
        { key: 'excise_tax', label: 'Excise tax (3%)', type: 'currency' },
      ],
    },
    {
      id: 'totals',
      name: 'Totals',
      hidden: true,
      fields: [
        { key: 'total_days', label: 'Total days', type: 'number', computed: true },
        { key: 'total_cost_p_day', label: 'Total cost per day', type: 'currency', computed: true },
        { key: 'total_r_cost', label: 'Total rental cost', type: 'currency', computed: true },
      ],
    },
    {
      id: 'vehicle',
      name: 'Vehicle Details',
      fields: [
        { key: 'make', label: 'Make', type: 'text' },
        { key: 'color', label: 'Color', type: 'text' },
        { key: 'model', label: 'Model', type: 'text' },
        { key: 'mileage', label: 'Mileage', type: 'number' },
        { key: 'year', label: 'Year', type: 'number' },
        { key: 'cargovan_vin', label: 'VIN number', type: 'text' },
        { key: 'license_plate', label: 'License plate', type: 'text' },
        { key: 'overage_cost', label: 'Overage cost per mile', type: 'currency' },
      ],
    },
    {
      id: 'signatures',
      name: 'Signatures',
      hidden: true,
      fields: [
        { key: 'signature', label: 'Renter signature', type: 'text' },
        { key: 'renter_signed_date', label: 'Renter signed date', type: 'date' },
        { key: 'customer_fullname', label: 'Renter printed name', type: 'text' },
        { key: 'owner_signed_date', label: 'Owner signed date', type: 'date' },
      ],
    },
  ],
};
